version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies...
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.1/2024-03-06/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
      - kubectl version --client
  pre_build:
    commands:
      - set -x
      - echo "Verifying AWS CLI and Docker"
      - aws --version
      - docker --version
      - aws sts get-caller-identity
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 390402565417.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=390402565417.dkr.ecr.us-west-2.amazonaws.com/nodejs-eks-app

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nodejs-eks-app .
      - docker tag nodejs-eks-app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPOSITORY_URI:latest
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-west-2 --name nodejs-eks-app
      - echo Verifying kubeconfig...
      - cat ~/.kube/config || echo "No kubeconfig found"
      - kubectl config current-context || echo "No context"
      - echo Testing access to cluster...
      - kubectl get nodes || echo "Failed to get nodes"
      - echo Applying Kubernetes manifests...
      - kubectl apply -f k8/ || echo "Failed to apply k8 manifests"

artifacts:
  files:
    - k8/service.yaml
    - k8/configmap.yaml
    - k8/deployment.yaml
