version: 0.2

phases:
  pre_build:
    commands:
      - set -x
      - echo "Verifying AWS CLI and Docker"
      - aws --version
      - docker --version
      - aws sts get-caller-identity
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 390402565417.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=390402565417.dkr.ecr.us-west-2.amazonaws.com/nodejs-eks-app

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nodejs-eks-app .
      - docker tag nodejs-eks-app:latest $REPOSITORY_URI:latest

  post_build:
    commands:
    - echo Pushing the Docker image...
    - docker push $REPOSITORY_URI:latest
    - aws eks update-kubeconfig --region us-west-2 --name nodejs-eks-app
    - cat ~/.kube/config || echo "No kube config found"
    - kubectl config get-contexts || echo "No context"
    - echo Updating kubeconfig...
    - aws eks update-kubeconfig --region us-west-2 --name nodejs-eks-app
    - kubectl version --client
    - kubectl get nodes
    - echo Deploying to EKS...
    - kubectl apply -f k8/

artifacts:
  files:
    - k8/service.yaml
    - k8/configmap.yaml
    - k8/deployment.yaml
