
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 390402565417.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=390402565417.dkr.ecr.us-east-1.amazonaws.com/my-app-task-test
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-app .
      - docker tag my-app:latest $REPO_URI:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPO_URI:latest
      - echo Generating imagedefinitions.json...
      - printf '[{"name":"my-app-task","imageUri":"%s"}]' $REPO_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
