apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: default
data:
  mapRoles: |
    - rolearn: arn:aws:iam::390402565417:role/service-role/codebuild-Mytest-project-service-role
      username: arn:aws:iam::390402565417:root
      groups:
        - system:masters