apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::390402565417:role/service-role/codebuild-Mytest-project-service-role
      username: codebuild
      groups:
        - system:masters