apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
